config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from accounts.forms import EmailAuthenticationForm
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import dashboard_view, root_view, profile_view, ForcedPasswordChangeView, user_create_view, edit_area_info_view, CustomPasswordResetView
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetCompleteView, PasswordResetDoneView

urlpatterns = [
    # ROOT = LOGIN
    path("", root_view, name="root"),
    path("dashboard/", dashboard_view, name="dashboard"),
    path(
        "area-info/edit/",
        edit_area_info_view,
        name="edit_area_info"
    ),
    # ACCOUNT APP
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="accounts/login.html",
            authentication_form=EmailAuthenticationForm,
        ),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
    "password-change/",
    ForcedPasswordChangeView.as_view(),
    name="password_change",
    ),
    path(
    "password-change/done/",
    auth_views.PasswordChangeDoneView.as_view(
        template_name="accounts/password_change_done.html",
    ),
    name="password_change_done",
    ),
    path("admin/", admin.site.urls),
    path("profile/", profile_view, name="profile"),
    path(
        "password-reset/",
        CustomPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(
        template_name="accounts/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
        template_name="accounts/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(
        template_name="accounts/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("users/create/", user_create_view, name="user_create"),
    path("saunas/", include("saunas.urls")),
    path("notebook/", include("notebook.urls")),
    path("classes/", include("classes.urls")),
    path("balance/", include("balance.urls")),
    path("vouchers/", include("vouchers.urls")),
    path("reports/", include("reports.urls")),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

vouchers/urls.py
from django.urls import path
from .views import voucher_search_view, voucher_create_view, voucher_redeem_view, voucher_edit_view, voucher_extend_view, voucher_transaction_view, voucher_logs_view, voucher_list_view

app_name = "vouchers"

urlpatterns = [ 
    path ("", voucher_search_view, name="voucher_search"),
    path("create/", voucher_create_view , name="voucher_create"),
    path(
    "<int:pk>/redeem/",
    voucher_redeem_view,
    name="voucher_redeem",
    ),
    path(
    "<int:pk>/edit/",
    voucher_edit_view,
    name="voucher_edit",
    ),
    path("<int:pk>/extend/", voucher_extend_view, name="voucher_extend"),
    path("<int:pk>/transaction/", voucher_transaction_view, name="voucher_transaction"),
    path("logs/", voucher_logs_view, name="voucher_logs"),
    path("all/", voucher_list_view, name="voucher_list"),
]

vouchers/models.py
from django.db import models
from django.conf import settings
from decimal import Decimal
from django.core.exceptions import ValidationError
from django.utils import timezone
from datetime import timedelta


class MPVCard(models.Model):
    code = models.CharField(max_length=10, unique=True)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        indexes = [
            models.Index(fields=["code"]),
        ]

    def __str__(self):
        return self.code


class Voucher(models.Model):

    class Type(models.TextChoices):
        MPV = "MPV", "MPV"
        SPV = "SPV", "SPV"
        OLD = "OLD", "STARY"

    class Status(models.TextChoices):
        ACTIVE = "active", "Active"
        USED = "used", "Used"
        ZERO_NOT_RETURNED = "zero_not_returned", "Zero – not returned"
        ZERO_RETURNED = "zero_returned", "Zero – returned"
        EXPIRED = "expired", "Expired"

    type = models.CharField(max_length=3, choices=Type.choices)

    # SPV / OLD
    code = models.CharField(max_length=20, blank=True)

    # MPV
    mpv_card = models.ForeignKey(
        MPVCard,
        on_delete=models.PROTECT,
        null=True,
        blank=True,
        related_name="vouchers",
    )

    client_name = models.CharField(max_length=150)
    receipt_number = models.CharField(max_length=150, blank=True)

    issue_date = models.DateTimeField(auto_now_add=True)

    expiry_date = models.DateField(blank=True, null=True)
    extended_until = models.DateField(null=True, blank=True)
    extended_reason = models.CharField(max_length=255, blank=True)

    seller = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="sold_vouchers"
    )

    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.ACTIVE,
    )

    # MPV
    value_total = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True,
    )

    value_remaining = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True,
    )

    # SPV
    service_name = models.CharField(max_length=200, blank=True)
    redeemed_at = models.DateTimeField(null=True, blank=True)

    notes = models.TextField(blank=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        indexes = [
            models.Index(fields=["code"]),
            models.Index(fields=["client_name"]),
            models.Index(fields=["status"]),
            models.Index(fields=["type"]),
            models.Index(fields=["issue_date"]),
        ]

    # ======================================
    # PROPERTY: is_expired
    # ======================================

    @property
    def is_expired(self):
        if not self.expiry_date and not self.extended_until:
            return False

        today = timezone.localdate()
        effective_expiry = self.extended_until or self.expiry_date
        return effective_expiry < today
    
    # ======================================
    # PROPERTY: effective_status
    # ======================================

    @property
    def effective_status(self):
        if self.status == self.Status.ACTIVE and self.is_expired:
            return self.Status.EXPIRED
        return self.status
    
    # ======================================
    # PROPERTY: display
    # ======================================

    @property
    def display_status(self):
        mapping = {
            "active": "AKTYWNY",
            "used": "ZUŻYTY",
            "expired": "WYGASŁ",
            "zero_not_returned": "WYKORZYSTANY – KARTA NIEODDANA",
            "zero_returned": "WYKORZYSTANY – KARTA ZWRÓCONA",
        }
        return mapping.get(self.effective_status, self.effective_status)

    @property
    def display_type(self):
        mapping = {
            "MPV": "MPV",
            "SPV": "SPV",
            "OLD": "STARY",
        }
        return mapping.get(self.type, self.type)
    
    @property
    def display_seller(self):
        if not self.seller:
            return "-"
        return self.seller.first_name or self.seller.email


    # ======================================
    # CLEAN LOGIC
    # ======================================

    def clean(self):

        today = timezone.localdate()

        # -----------------------------
        # TYPE VALIDATION
        # -----------------------------

        if self.type == self.Type.MPV:

            if self.value_total is None:
                raise ValidationError("MPV musi mieć wartość początkową.")

            if self.value_total < Decimal("0.00"):
                raise ValidationError("Wartość MPV nie może być ujemna.")

            # ustawienie początkowego salda przy tworzeniu
            if self.pk is None:
                self.value_remaining = self.value_total

            # blokada aktywnej karty
            existing_active = Voucher.objects.filter(
                mpv_card=self.mpv_card,
                type=self.Type.MPV,
                status__in=[
                    self.Status.ACTIVE,
                    self.Status.ZERO_NOT_RETURNED
                ]
            ).exclude(pk=self.pk)

            if existing_active.exists():
                raise ValidationError(
                    "Ta karta ma już aktywny voucher."
                )

        else:
            # SPV / OLD muszą mieć kod
            if not self.code:
                raise ValidationError("Voucher musi mieć kod.")

            if self.type == self.Type.MPV and self.mpv_card is None:
                raise ValidationError("MPV musi mieć przypisaną kartę.")


        # -----------------------------
        # SPV SPECIFIC
        # -----------------------------

        if self.type == self.Type.SPV:

            if not self.service_name:
                raise ValidationError("SPV musi mieć nazwę usługi.")

            if self.value_remaining:
                raise ValidationError("SPV nie może mieć value_remaining.")

        # -----------------------------
        # EXPIRY DEFAULT
        # -----------------------------

        if not self.expiry_date:

            if self.type == self.Type.MPV:
                self.expiry_date = today + timedelta(days=180)

            elif self.type == self.Type.SPV:
                self.expiry_date = today + timedelta(days=90)

        # -----------------------------
        # AUTO STATUS EXPIRED
        # -----------------------------

        if self.is_expired and self.status == self.Status.ACTIVE:
            self.status = self.Status.EXPIRED

    def __str__(self):
        if self.type == self.Type.MPV:
            return f"MPV {self.mpv_card.code} – {self.client_name}"
        return f"{self.type} {self.code} – {self.client_name}"



class MPVTransaction(models.Model):

    voucher = models.ForeignKey(
        Voucher,
        on_delete=models.CASCADE,
        related_name="transactions"
    )

    amount = models.DecimalField(
        max_digits=10,
        decimal_places=2
    )

    created_at = models.DateTimeField(auto_now_add=True)

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True
    )

    note = models.CharField(max_length=255, blank=True)

    class Meta:
        ordering = ["-created_at"]

    def clean(self):

        # 🔐 zabezpieczenie — jeśli voucher nie jest ustawiony
        if not self.voucher_id:
            raise ValidationError("Voucher nie został przypisany.")

        if self.voucher.type != Voucher.Type.MPV:
            raise ValidationError("Transakcje tylko dla MPV.")

        if self.amount is None or self.amount <= Decimal("0.00"):
            raise ValidationError("Kwota musi być dodatnia.")

        if self.voucher.value_remaining is None:
            raise ValidationError("Voucher nie ma salda.")

        if self.amount > self.voucher.value_remaining:
            raise ValidationError("Brak wystarczających środków.")

    def save(self, *args, **kwargs):

        is_new = self.pk is None

        super().save(*args, **kwargs)

        if is_new:
            voucher = self.voucher
            voucher.value_remaining -= self.amount

            if voucher.value_remaining <= Decimal("0.00"):
                voucher.value_remaining = Decimal("0.00")

            voucher.save(update_fields=["value_remaining", "updated_at"])

    def __str__(self):
        return f"{self.voucher} – {self.amount}"


class VoucherLog(models.Model):

    class Action(models.TextChoices):
        CREATED = "created", "Created"
        EDITED = "edited", "Edited"
        EXTENDED = "extended", "Extended"
        STATUS_CHANGED = "status_changed", "Status changed"
        TRANSACTION = "transaction", "MPV transaction"

    voucher = models.ForeignKey(
        Voucher,
        on_delete=models.CASCADE,
        related_name="logs"
    )

    action = models.CharField(max_length=30, choices=Action.choices)

    performed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True
    )

    description = models.TextField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.voucher} – {self.action}"

templates/vouchers/create.html
{% extends "base.html" %}
{% block content %}

<h1>Dodaj voucher</h1>
{% if form.errors %}
<div style="color:red">
  {{ form.errors }}
</div>
{% endif %}

<form method="post">
  {% csrf_token %}

  <div class="mb-3">
    <label class="form-label">Typ</label>
    {{ form.type }}
  </div>

  <div id="code" class="mb-3">
    <label class="form-label">Kod</label>
    {{ form.code }}
  </div>

  <div id="mpv_card_code" class="mb-3">
    <label class="form-label">Karta MPV</label>
    {{ form.mpv_card_code }}
  </div>

  <div id="value_total" class="mb-3">
    <label class="form-label">Wartość</label>
    {{ form.value_total }}
  </div>

  <div class="mb-3">
    <label class="form-label">Imię i nazwisko klienta</label>
    {{ form.client_name }}
  </div>

  <div id="service_name" class="mb-3">
    <label class="form-label">Nazwa usługi</label>
    {{ form.service_name }}
  </div>

  <div id="receipt_number" class="mb-3">
    <label class="form-label">Nr paragonu</label>
    {{ form.receipt_number }}
  </div>

  <div id="expiry_date" class="mb-3">
    <label class="form-label">Data ważności</label>
    {{ form.expiry_date }}
  </div>

  <div class="mb-3">
    <label class="form-label">Notatki</label>
    {{ form.notes }}
  </div>

  <button type="submit" class="btn btn-primary">
    Zapisz
  </button>

</form>

{% endblock %}

{% block scripts %}
<script>
document.addEventListener("DOMContentLoaded", function () {

  const typeSelect = document.getElementById("id_type");

  const codeField = document.getElementById("code");
  const mpvCardField = document.getElementById("mpv_card_code");
  const valueField = document.getElementById("value_total");
  const serviceField = document.getElementById("service_name");
  const receiptField = document.getElementById("receipt_number");
  const expiryField = document.getElementById("expiry_date");

  function toggleFields() {

    const type = typeSelect.value;

    // reset wszystko
    codeField.style.display = "none";
    mpvCardField.style.display = "none";
    valueField.style.display = "none";
    serviceField.style.display = "none";
    receiptField.style.display = "none";
    expiryField.style.display = "none";

    if (type === "MPV") {
      mpvCardField.style.display = "block";
      valueField.style.display = "block";
      receiptField.style.display = "block";
    }

    else if (type === "SPV") {
      codeField.style.display = "block";
      serviceField.style.display = "block";
      receiptField.style.display = "block";
    }

    else if (type === "OLD") {
      codeField.style.display = "block";
      serviceField.style.display = "block";
      expiryField.style.display = "block";
    }
  }

  toggleFields();
  typeSelect.addEventListener("change", toggleFields);
});
</script>

{% endblock %}

templates/vouchers/edit.html
{% extends "base.html" %}

{% block content %}

<h3>Edytuj voucher</h3>
<input type="hidden" name="next" value="{{ request.GET.next }}">

<form method="post">
  {% csrf_token %}
  
  {{ form.non_field_errors }}

  {% for field in form %}
    <div class="mb-3">
      <label class="form-label">{{ field.label }}</label>
      {{ field }}
      {% if field.errors %}
        <div class="text-danger small">
          {{ field.errors }}
        </div>
      {% endif %}
    </div>
  {% endfor %}

  {% if not form.fields.client_name.disabled %}
    <button type="submit" class="btn btn-primary">
      Zapisz zmiany
    </button>
  {% endif %}

</form>

{% endblock %}

templates/vouchers/extend.html
{% extends "base.html" %}
{% block content %}
<h3>Przedłuż voucher</h3>

<div class="card p-4">
    <strong>
        {% if voucher.type == "MPV" %}
            MPV – {{ voucher.mpv_card.code }}
        {% else %}
            {{ voucher.display_type }} – {{ voucher.code }}
        {% endif %}
    </strong>

    <form method="post" class="mt-3">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
        <div class="mb-3">
            <label>Nowa data ważności</label>
            {{ form.extended_until }}
        </div>

        <div class="mb-3">
            <label>Powód przedłużenia</label>
            {{ form.extended_reason }}
        </div>

        <button class="btn btn-warning w-100">
            Zapisz przedłużenie
        </button>
    </form>
</div>
{% endblock %}

templates/vouchers/logs.html
{% extends "base.html" %}
{% block content %}

<h4>Historia operacji</h4>

<table class="table table-striped align-middle">
  <thead>
    <tr>
      <th>Data</th>
      <th>Voucher</th>
      <th>Akcja</th>
      <th>Opis</th>
      <th>Użytkownik</th>
    </tr>
  </thead>
  <tbody>
    {% for log in page_obj %}
    <tr>
      <td>{{ log.created_at|date:"d.m.Y H:i" }}</td>
      <td>
        {% if log.voucher.type == "MPV" %}
          MPV – {{ log.voucher.mpv_card.code }}
        {% else %}
          {{ log.voucher.get_type_display }} – {{ log.voucher.code }}
        {% endif %}
      </td>
      <td>{{ log.get_action_display }}</td>
      <td>{{ log.description }}</td>
      <td>
        {% if log.performed_by %}
          {{ log.performed_by.first_name }} {{ log.performed_by.last_name }}
        {% else %}
          —
        {% endif %}
      </td>
    </tr>
    {% empty %}
      <tr>
        <td colspan="5" class="text-muted text-center">Brak logów</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

{% if page_obj.has_other_pages %}
<nav class="mt-4">
  <ul class="pagination justify-content-center">

    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          &laquo;
        </a>
      </li>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
      {% if page_obj.number == num %}
        <li class="page-item active">
          <span class="page-link">{{ num }}</span>
        </li>
      {% elif num >= page_obj.number|add:"-2" and num <= page_obj.number|add:"2" %}
        <li class="page-item">
          <a class="page-link" href="?page={{ num }}">{{ num }}</a>
        </li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          &raquo;
        </a>
      </li>
    {% endif %}

  </ul>
</nav>
{% endif %}

{% endblock %}

templates/vouchers/search.html
{% extends "base.html" %}
{% load permissions %}
{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3">
  <h1>Wyszukaj voucher</h1>
   {% if request.user|can:"create_vouchers" %}
    <a href="{% url 'vouchers:voucher_create' %}"
      class="btn btn-sm btn-outline-warning">
      Dodaj Voucher
    </a>
   {% endif %}
    <a href="{% url 'vouchers:voucher_list' %}"
      class="btn btn-outline-primary ms-2">
      Pokaż wszystkie
    </a>
</div>

<form method="get" class="mb-4">
  <div class="input-group">
    <input type="text"
           name="q"
           value="{{ query }}"
           class="form-control"
           placeholder="Kod / MPV karta / Klient">
    <button class="btn btn-primary">
      Szukaj
    </button>
  </div>
</form>

{% if query %}

  <h5>Wyniki: {{ results|length }}</h5>

  {% for v in results %}
    <div class="card mb-3 shadow-sm border-0">
      <div class="card-body">

        <div class="row align-items-start">

          <!-- LEWA STRONA -->
          <div class="col-md-5">

            <div class="d-flex align-items-center gap-2">
              <h5 class="mb-0 fw-bold">
                {% if v.type == "MPV" %}
                  MPV – {{ v.mpv_card.code }}
                {% else %}
                  {{ v.display_type }} – {{ v.code }}
                {% endif %}
              </h5>

              {% if v.effective_status == "used" %}
                <span class="badge bg-success">{{ v.display_status }}</span>
              {% elif v.effective_status == "expired" %}
                <span class="badge bg-danger">{{ v.display_status }}</span>
              {% elif v.effective_status == "active" %}
                <span class="badge bg-primary">{{ v.display_status }}</span>
              {% elif v.effective_status == "zero_not_returned" %}
                <span class="badge bg-warning text-dark">{{ v.display_status }}</span>
              {% elif v.effective_status == "zero_returned" %}
                <span class="badge bg-secondary">{{ v.display_status }}</span>
              {% endif %}
            </div>

            <div class="mt-2">
              <strong>{{ v.client_name }}</strong>
            </div>

            <div class="mt-2">
              {% if v.type == "MPV" %}
                Saldo: {{ v.value_remaining }} / {{ v.value_total }}
              {% else %}
                {{ v.service_name }}
              {% endif %}
            </div>

            <!-- JEDNA LINIA: WYDANY | WYGASA | SELLER -->
            <div class="text-muted small mt-2">
              Wydany: {{ v.issue_date|date:"d.m.Y H:i" }} |
              Wygasa:
              {% if v.extended_until %}
                {{ v.extended_until|date:"d.m.Y" }}
              {% else %}
                {{ v.expiry_date|date:"d.m.Y" }}
              {% endif %}
              |
              Sprzedawca: {{ v.display_seller }}
            </div>

          </div>


          <!-- ŚRODEK – NOTES -->
          <div class="col-md-4">
            {% if v.notes %}
              <div class="small">
                <strong>NOTES:</strong>
                <div class="mt-1">
                  {{ v.notes }}
                </div>
              </div>
            {% endif %}
          </div>


          <!-- PRAWA STRONA – PRZYCISKI -->
          <div class="col-md-3 text-end d-flex flex-column gap-2">

            {# ===== EDYCJA ===== #}
            {% if request.user|can:"edit_vouchers" and v.effective_status == "active" %}
              <a href="{% url 'vouchers:voucher_edit' v.pk %}?next={{ request.get_full_path }}" class="btn btn-sm w-100 btn-outline-light action-btn">
                Edycja
              </a>
            {% endif %}

            {# ===== PRZEDŁUŻ ===== #}
            {% if request.user|can:"extend_vouchers" %}
              {% if v.effective_status == "active" or v.effective_status == "expired" %}
                <a href="{% url 'vouchers:voucher_extend' v.pk %}?next={{ request.get_full_path }}"
                  class="btn btn-sm w-100 btn-outline-warning action-btn">
                  Przedłuż
                </a>
              {% endif %}
            {% endif %}


            {# ===== MPV ===== #}
            {% if request.user|can:"mpv_transactions" and v.type == "MPV" %}
              {% if v.effective_status == "active" %}
                <a href="{% url 'vouchers:voucher_transaction' v.pk %}?next={{ request.get_full_path }}" class="btn btn-sm w-100 btn-outline-info action-btn">
                  Transakcje
                </a>
              {% endif %}
            {% endif %}

            {# ===== SPV / OLD ===== #}
            {% if request.user|can:"redeem_vouchers" and v.type != "MPV" and v.effective_status == "active" %}
              <form method="post" action="{% url 'vouchers:voucher_redeem' v.pk %}?next={{ request.get_full_path }}">
                {% csrf_token %}
                <button type="submit" class="btn btn-sm w-100 btn-outline-success action-btn">
                  Oznacz jako zużyty
                </button>
              </form>
            {% endif %}


          </div>


        </div>

      </div>
    </div>
    {% empty %}
    <p class="text-muted">Brak wyników</p>
    {% endfor %}



{% endif %}

{% if page_obj.has_other_pages %}
<nav class="mt-3">
  <ul class="pagination justify-content-center">

    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?q={{ query }}&page={{ page_obj.previous_page_number }}">
          &laquo;
        </a>
      </li>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
      <li class="page-item {% if page_obj.number == num %}active{% endif %}">
        <a class="page-link" href="?q={{ query }}&page={{ num }}">
          {{ num }}
        </a>
      </li>
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?q={{ query }}&page={{ page_obj.next_page_number }}">
          &raquo;
        </a>
      </li>
    {% endif %}

  </ul>
</nav>
{% endif %}


{% endblock %}

templates/vouchers/transaction.html
{% extends "base.html" %}
{% block content %}
<h3>Transakcja MPV</h3>

<div class="card p-4">

    <strong>
        MPV – {{ voucher.mpv_card.code }}
    </strong>

    <div class="mb-2">
        Saldo: {{ voucher.value_remaining }} / {{ voucher.value_total }}
    </div>
    {% if form.errors %}
     <div class="alert alert-danger">
        {{ form.errors }}
     </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
        <div class="mb-3">
            <label>Kwota</label>
            {{ form.amount }}
        </div>

        <div class="mb-3">
            <label>Notatka</label>
            {{ form.note }}
        </div>

        <button class="btn btn-info w-100">
            Zapisz transakcję
        </button>
    </form>
</div>
{% if show_modal %}
<div class="modal fade show" style="display:block; background: rgba(0,0,0,0.6);">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

            <div class="modal-header">
                <h5 class="modal-title">Karta wyzerowana</h5>
            </div>

            <div class="modal-body">
                Czy karta została oddana do recepcji?
            </div>

            <div class="modal-footer">

                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="confirm_return" value="no">
                    <button class="btn btn-warning">Nie</button>
                </form>

                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="confirm_return" value="yes">
                    <button class="btn btn-success">Tak</button>
                </form>

            </div>
        </div>
    </div>
</div>
{% endif %}


{% endblock %}

templates/vouchers/voucher_list.html
{% extends "base.html" %}
{% block title %}Lista voucherów{% endblock %}

{% block content %}

<h3 class="section-title mb-4">Lista voucherów</h3>

<form method="get" class="row g-3 mb-4">

  <div class="col-md-3">
    <label class="form-label">Typ</label>
    <select name="type" class="form-control">
      <option value="ALL">Wszystkie</option>
      <option value="SPV" {% if voucher_type == "SPV" %}selected{% endif %}>SPV</option>
      <option value="MPV" {% if voucher_type == "MPV" %}selected{% endif %}>MPV</option>
      <option value="OLD" {% if voucher_type == "OLD" %}selected{% endif %}>OLD</option>
    </select>
  </div>

  <div class="col-md-3">
    <label class="form-label">Od</label>
    <input type="date" name="from" value="{{ date_from }}" class="form-control">
  </div>

  <div class="col-md-3">
    <label class="form-label">Do</label>
    <input type="date" name="to" value="{{ date_to }}" class="form-control">
  </div>

  <div class="col-md-2">
    <label class="form-label">Sortowanie</label>
    <select name="order" class="form-control">
      <option value="asc" {% if order == "asc" %}selected{% endif %}>
        Najstarsze
      </option>
      <option value="desc" {% if order == "desc" %}selected{% endif %}>
        Najnowsze
      </option>
    </select>
  </div>

  <div class="col-md-1 d-flex align-items-end">
    <button type="submit" class="btn btn-primary w-100">
      Filtruj
    </button>
  </div>

</form>


<div class="card">
  <div class="card-body">

    <table class="table table-sm">
      <thead>
        <tr>
          <th>Typ</th>
          <th>Kod</th>
          <th>Klient</th>
          <th>Data</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>

        {% for voucher in page_obj %}
          <tr>
            <td>{{ voucher.display_type }}</td>
            <td>{{ voucher.code }}</td>
            <td>{{ voucher.client_name }}</td>
            <td>{{ voucher.issue_date|date:"d.m.Y H:i" }}</td>
            <td>{{ voucher.status }}</td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="5">Brak wyników</td>
          </tr>
        {% endfor %}

      </tbody>
    </table>

  </div>
</div>

{% if page_obj.has_other_pages %}
<nav class="mt-3">
  <ul class="pagination">

    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link"
           href="?page={{ page_obj.previous_page_number }}">
          ←
        </a>
      </li>
    {% endif %}

    <li class="page-item disabled">
      <span class="page-link">
        {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
      </span>
    </li>

    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link"
           href="?page={{ page_obj.next_page_number }}">
          →
        </a>
      </li>
    {% endif %}

  </ul>
</nav>
{% endif %}

{% endblock %}